version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: galoucura
      POSTGRES_DB: meu_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./back
    container_name: backend-app
    environment:
      DATABASE_URL: postgres://postgres:galoucura@postgres-db:5432/postgres
      MONGO_URL: mongodb+srv://pereiradiasrian:galoucura@cluster0.lncgv.mongodb.net/Users?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: secret_key12345
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build: ./front/react-auth-app
    container_name: frontend-app
    ports:
      - "5173:5173"
    volumes:
      - ./front/react-auth-app:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  pgdata: